# Generated by Django 4.2 on 2026-01-19 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_chapter_alter_question_options_question_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('quiz', 'Quiz'), ('coding', 'Coding Challenge')], default='quiz', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=100, help_text='Points awarded for completing challenge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='questions_completed',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(default=1, help_text='Teaching material and learning content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscore',
            name='challenges_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='chapters_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, help_text='Code snippet or context'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint for the question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='story',
            field=models.TextField(help_text='The question description'),
        ),
        migrations.AddField(
            model_name='question',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.challenge'),
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0, help_text='Score earned in this attempt')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to='game.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
